version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: beautifulsoup4
    versions:
    - 4.9.3
  - dependency-name: colorama
    versions:
    - 0.4.4
